version: '3.4'

services:
  scrappingbackend:
    image: scrappingbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
